version: '3'
services:
  db:
    image: postgres:13.4-alpine
    container_name: postgres_footy_db
    env_file:
      - .env
    volumes:
      - postgres-db:/data/postgres
    ports:
     - "5432:5432"

volumes:
  postgres-db:
    driver: local