name: Football Data pipeline

on:
  push

jobs:
  testing-pipeline:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.11]
      steps:
        - uses: actions/checkout@v2

        - name: Set up Python all python versions
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64

        - name: Install pip
          run: | 
             echo "Installing pip"
             python -m pip install --upgrade pip

        - name: Install PyLint
          run: |
             echo "Installing pylint"
             pip install pylint
        
        - name: Analysing the code with pylint
          run: |
            "echo" Checking For Code Funk
            find . -name '*.py' -exec pylint {} \;

        - name: Install dependencies
          run: |
            echo "Installing Dependencies"
            pip install -r requirements.txt
            pip install -e .

        - name: Run DataframeUtils Test
          run: |
            echo "Launching DataframeUtils tests"
            python -m unittest tests/test_dataframe_utils.py

        - name: Run PostgresUtils Test
          run: |
             echo "Launching PostgresUtils Tests"
             python -m unittest tests/test_postgres.py

        - name: Run SeasonDates Tests
          run: |
             echo "Launching SeasonDates Tests"
             python -m unittest tests/test_season_dates.py