name: Football Data pipeline

on:
  push

jobs:
  testing-pipeline:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.11]

      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            architecture: x64
            cache: "pip"

        - name: Install dependencies
          run: make install-dependencies

        - name: Get Changed Files
          id: changed-python-files
          uses: tj-actions/changed-files@v44
          with:
            files: |
              *.py
              **/*.py

        - name: Format
          if: always() && steps.changed-python-files.outputs.any_changed == 'true'
          run: |
            make black-format-check FILES="${{ steps.changed-python-files.outputs.all_changed_files }}"
            make isort-import-check FILES="${{ steps.changed-python-files.outputs.all_changed_files }}"

#        - name: Typecheck
#          if: always() && steps.changed-python-files.outputs.any_changed == 'true'
#          run: make mypy-check FILES="${{ steps.changed-python-files.outputs.all_changed_files }}"

        - name: Lint
          if: always() && steps.changed-python-files.outputs.any_changed == 'true'
          run: make ruff-lint-check FILES="${{ steps.changed-python-files.outputs.all_changed_files }}"

        - name: Run DataframeUtils Test
          run: |
            echo "Launching DataframeUtils tests"
            python -m unittest tests/test_dataframe_utils.py

        - name: Run ColumnUtils Test
          run: |
            echo "launching ColumnUtils Tests"
            python -m unittest tests/test_column_utils.py

        - name: Run PostgresUtils Test
          run: |
             echo "Launching PostgresUtils Tests"
             python -m unittest tests/test_postgres.py

        - name: Run SeasonDates Tests
          run: |
             echo "Launching SeasonDates Tests"
             python -m unittest tests/test_season_dates.py